name: Deploy to Minikube on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to Minikube
        run: |
          minikube start
          kubectl config use-context minikube
          kubectl apply -f kube/kube-deployment.yaml 
          kubectl apply -f kube/kube-service.yaml 
        shell: bash
        continue-on-error: true

      - name: Verify Deployment
        run: |
          kubectl get deployment
          kubectl get svc
        shell: bash
        continue-on-error: true